import * as vscode from "vscode";
import * as path from "path";

const GEMINI_API_KEY = "AIzaSyB2G6whTN2B7LPw6Y19MLTNjebE_TH0jQI";
const GEMINI_ENDPOINT = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${GEMINI_API_KEY}`;

export async function generateDocumentation() {
  const editor = vscode.window.activeTextEditor;
  if (!editor) {
    vscode.window.showErrorMessage("Please open a file to generate documentation.");
    return;
  }

  const selection = editor.selection;
  const selectedText = editor.document.getText(selection);

  if (!selectedText) {
    vscode.window.showWarningMessage("Highlight some code first!");
    return;
  }

  await vscode.window.withProgress({
    location: vscode.ProgressLocation.Notification,
    title: "Gemini: Contacting AI Engine...",
    cancellable: false
  }, async () => {
    try {
      const response = await fetch(GEMINI_ENDPOINT, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          contents: [{ parts: [{ text: `Generate a brief overview and documentation for this code:\n\n${selectedText}` }] }]
        })
      });

      const data: any = await response.json();
      const aiResponse = data.candidates?.[0]?.content?.parts?.[0]?.text || "No response from AI.";

      const documentation = `
# AI Documentation Report
**File Analyzed**: ${path.basename(editor.document.fileName)}
**Provider**: Gemini 1.5 Flash

## AI Analysis
${aiResponse}

---
*Generated by Internal Gemini VSIX Service*
      `;

      const doc = await vscode.workspace.openTextDocument({ content: documentation, language: "markdown" });
      await vscode.window.showTextDocument(doc, vscode.ViewColumn.Beside);
    } catch (error: any) {
      vscode.window.showErrorMessage(`Gemini API Error: ${error.message}`);
    }
  });
}
